export const commandManifest = [
  { command: 'accounts', description: 'List connected accounts' },
  { command: 'api get', description: 'Make an authenticated raw GET request' },
  { command: 'api post', description: 'Make an authenticated raw POST request' },
  { command: 'archive', description: 'Archive a chat' },
  { command: 'assets download', description: 'Download an asset' },
  { command: 'assets upload', description: 'Upload an asset' },
  { command: 'auth login', description: 'Authenticate with local Beeper Desktop' },
  { command: 'auth logout', description: 'Remove local credentials' },
  { command: 'auth status', description: 'Show local auth state' },
  { command: 'chat', description: 'Show one chat' },
  { command: 'chat open', description: 'Alias for focus' },
  { command: 'chats', description: 'List chats' },
  { command: 'chats search', description: 'Search chats' },
  { command: 'clear-draft', description: 'Clear a chat draft' },
  { command: 'commands', description: 'Print the command manifest' },
  { command: 'config get', description: 'Print CLI configuration' },
  { command: 'config path', description: 'Print the config file path' },
  { command: 'config reset', description: 'Reset CLI configuration' },
  { command: 'config set', description: 'Set CLI configuration' },
  { command: 'contacts search', description: 'Search contacts' },
  { command: 'create-chat', description: 'Create a chat' },
  { command: 'current-user', description: 'Show the OAuth userinfo response' },
  { command: 'delete-message', description: 'Delete a message' },
  { command: 'doctor', description: 'Check Desktop API readiness' },
  { command: 'draft', description: 'Set a chat draft' },
  { command: 'edit', description: 'Edit a message' },
  { command: 'focus', description: 'Focus Beeper Desktop or one chat' },
  { command: 'llm', description: 'Print compact CLI help for agents' },
  { command: 'message', description: 'Show one message' },
  { command: 'mark-read', description: 'Alias for read' },
  { command: 'mark-unread', description: 'Alias for unread' },
  { command: 'messages', description: 'List messages in a chat' },
  { command: 'messages search', description: 'Search messages' },
  { command: 'mute', description: 'Mute a chat' },
  { command: 'notify-anyway', description: 'Notify anyway for a chat' },
  { command: 'react', description: 'Add a reaction' },
  { command: 'read', description: 'Mark a chat read' },
  { command: 'remind', description: 'Set a chat reminder' },
  { command: 'reply', description: 'Reply to a message' },
  { command: 'reply-file', description: 'Reply to a message with a file attachment' },
  { command: 'rpc', description: 'Run JSONL command RPC over stdin/stdout' },
  { command: 'search', description: 'Search chats and messages' },
  { command: 'send', description: 'Send a message' },
  { command: 'send-file', description: 'Send a file attachment' },
  { command: 'shell', description: 'Run an interactive Beeper CLI shell' },
  { command: 'start-chat', description: 'Start a chat with participants' },
  { command: 'status', description: 'Show Desktop API server info' },
  { command: 'tail', description: 'Alias for watch' },
  { command: 'thread', description: 'Alias for chat' },
  { command: 'threads', description: 'Alias for chats' },
  { command: 'unarchive', description: 'Unarchive a chat' },
  { command: 'unmute', description: 'Unmute a chat' },
  { command: 'unreact', description: 'Remove a reaction' },
  { command: 'unread', description: 'Mark a chat unread' },
  { command: 'unremind', description: 'Clear a chat reminder' },
  { command: 'watch', description: 'Stream Desktop API WebSocket events' },
  { command: 'whoami', description: 'Alias for current-user' },
]
